### PR TITLE
Integrate domain-uxv and domain-sensor ontologies created by NTUA

### PR DESCRIPTION
**Pull request by maravger**
Two new ontologies, called omn-domain-uxv and omn-domain-sensor, have been implemented by NTUA as a part of the SAMANT open call (http://samant.lab.netmode.ntua.gr) of the RAWFIE project (http://www.rawfie.eu).

### CODE REVIEW

**Comment by AlexanderWillner** [comment]
Thanks, we'll check...

**Comment by JonasLenny** [comment]
Hey guys, sry for the late response. The tool is running again, but there are some errors in the ontology "http://www.loa-cnr.it/ontologies/DUL.owl".
You can see the log-file when you click on "Details" at "continuous-integration/travis-ci/pr" (or [here](https://travis-ci.org/w3c/omn/builds/293618990?utm_source=github_status&utm_medium=notification)) . However, the log file is too long and you have to use the raw-file to see the errors. You can find them at the end of the file. You can search "BUILD SUCCESSFUL" in the file to get directly to them.

**Comment by maravger** [comment]
Hmm I see. We've just imported some attributes from http://www.loa-cnr.it/ontologies/DUL.owl, so I'm not really sure about the mistakes within the ontology. Do you have any clue about how we could overcome this?

**Comment by JonasLenny** [comment]
I'm going to modify the validator to ignore external ontologies and will let you know when it's done.

**Comment by maravger** [comment]
thanks!

**Comment by JonasLenny** [comment]
Ok, I cannot exclude external ontologies without a valid URL. That's why I put your ontologies into a subfolder ("ontologies/unchecked/") which will be ignored during the tests.
These changes (and your ontologies) are already merged with the Master-branch, so if you are fine with it, I will close this pull request.

**Comment by maravger** [comment]
This is fine for us Jonas, thanks! You can close the request.

**Pull request closed without merging**
